name: CI
on: [push, pull_request]
jobs:
  lint-and-dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: envs/snakemake.yml
          cache-environment: true
      - name: Snakemake lint
        shell: bash -l {0}
        run: |
          snakemake --lint
      - name: Snakemake dry-run
        shell: bash -l {0}
        run: |
          snakemake -n --use-conda --cores 1
